name: walker2d
benchmark: walker2d
num_iters: 500
num_init: 50
parameters: null
bounds: [
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1],
  [-1, 1]
]
noise_std: 0.01